language: node_js

node_js:
  - 'node'
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add nyc coveralls

install:
  - yarn --frozen-lockfile --non-interactive

script:
  - yarn test:coverage

after_success:
  - yarn coverage